version: '3'
services:
  opensearch-cl1-node1:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-cl1-node1
    environment:
      - cluster.name=opensearch-cl1-cluster
      - node.name=opensearch-cl1-node1
      - discovery.seed_hosts=opensearch-cl1-node1,opensearch-cl-node2,opensearch-cl-node3
      - cluster.initial_master_nodes=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl-node3
      - bootstrap.memory_lock=false # along with the memlock settings below, disables swapping
      - node.store.allow_mmap=false # AP: so vm.max_map_count bootstrap check will pass - but don't do in prod it degrades perf
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-cl1-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-cl1-node2:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-cl1-node2
    environment:
      - cluster.name=opensearch-cl1-cluster
      - node.name=opensearch-cl1-node2
      - discovery.seed_hosts=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl-node3
      - cluster.initial_master_nodes=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl-node3
      - bootstrap.memory_lock=false
      - node.store.allow_mmap=false
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-cl1-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-cl1-node3:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-cl1-node3
    environment:
      - cluster.name=opensearch-cl1-cluster
      - node.name=opensearch-cl1-node3
      - discovery.seed_hosts=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl-node3
      - cluster.initial_master_nodes=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl-node3
      - bootstrap.memory_lock=false
      - node.store.allow_mmap=false
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-cl1-data3:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-cl2-node1:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-cl2-node1
    environment:
      - cluster.name=opensearch-cl2-cluster
      - node.name=opensearch-cl2-node1
      - discovery.seed_hosts=opensearch-cl2-node1,opensearch-c2-node2,opensearch-c2-node3
      - cluster.initial_master_nodes=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-c2-node3
      - bootstrap.memory_lock=false
      - node.store.allow_mmap=false
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-cl2-data1:/usr/share/opensearch/data
    ports:
      - 9201:9200
    networks:
      - opensearch-net
  opensearch-cl2-node2:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-cl2-node2
    environment:
      - cluster.name=opensearch-cl2-cluster
      - node.name=opensearch-cl2-node2
      - discovery.seed_hosts=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-c2-node3
      - cluster.initial_master_nodes=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-c2-node3
      - bootstrap.memory_lock=false
      - node.store.allow_mmap=false
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-cl2-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-cl2-node3:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-cl2-node3
    environment:
      - cluster.name=opensearch-cl2-cluster
      - node.name=opensearch-cl2-node3
      - discovery.seed_hosts=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-c2-node3
      - cluster.initial_master_nodes=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-c2-node3
      - bootstrap.memory_lock=false
      - node.store.allow_mmap=false
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-cl2-data3:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-dashboards-cl1:
    image: opensearchproject/opensearch-dashboards:2.6.0
    container_name: opensearch-dashboards-cl1
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-cl1-node1:9200","https://opensearch-cl1-node2:9200","https://opensearch-cl1-node3:9200"]'
    networks:
      - opensearch-net
  opensearch-dashboards-cl2:
    image: opensearchproject/opensearch-dashboards:2.6.0
    container_name: opensearch-dashboards-cl2
    ports:
      - 5602:5601
    expose:
      - "5602"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-cl2-node1:9200","https://opensearch-cl2-node2:9200","https://opensearch-cl2-node3:9200"]'
    networks:
      - opensearch-net

volumes:
  opensearch-cl1-data1:
  opensearch-cl1-data2:
  opensearch-cl1-data3:
  opensearch-cl2-data1:
  opensearch-cl2-data2:
  opensearch-cl2-data3:

# explicitly set name, otherwise the docker network name is prepended with the folder (project) name
networks:
  opensearch-net:
    name: opensearch-net